
knp_snappy:
    pdf:
        enabled:    true
        binary:     '"%env(WKHTMLTOPDF_PATH)%"' # Add double quotes around the binary path
        options:    []
    image:
        enabled: true
        binary: '%env(WKHTMLTOIMAGE_PATH)%'
        options: []